### ISSUE TITLE
All of your variants are shown in player profile menu.

### ISSUE THREAD

**Issue by ghost** [ErrorNull0/enZombies#2]
I suppose it's not a big bad unavoidable bug, Is there a property your forgetting to exclude them from this menu?
Looks like a debugging feature you never turned off?
Also Make nude living characters :D

**Comment by ErrorNull0** [comment]
sorry for the delay in response. i don't often check the issues tab. all the zombies showing up in the player profile menu is a side-effect of creating these zombies using the UMA player profile assets. on the plus side, you can select one of them and play the game as any of those zombies lol.

'living' characters like NPCs? the closest to non zombie characters would be zombies that don't have any blood/wound texture on them and. but the would still have similar walking animations as zombies. i have since created enZombiesTraders mod (avail here on this github) which are essentially zombies that look like alive traders that don't attack players. should i make nude versions of the female traders? hmmmm... maybe :)
